version: "3.8"
services:
  web:
    image: rvc-serverless:150620251050
    container_name: rvc-container-runpod
    command: ["python3", "/app/runpod_handler.py"]
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - S3_ENABLED=${S3_ENABLED:-false}
      - BUCKET_AREA=${BUCKET_AREA}
      - S3_KEY_PREFIX=${S3_KEY_PREFIX}
      - BUCKET_ENDPOINT_URL=${BUCKET_ENDPOINT_URL}
      - BUCKET_ACCESS_KEY_ID=${BUCKET_ACCESS_KEY_ID}
      - BUCKET_SECRET_ACCESS_KEY=${BUCKET_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
    volumes:
      - ./weights:/app/assets/weights
      - ./opt:/app/opt
      - ./logs:/app/logs
      - ./infer/lib:/app/infer/lib
      - ./rvc_api.py:/app/rvc_api.py
      - ./runpod_handler.py:/app/runpod_handler.py
      - ./services:/app/services
      - ./test_input.json:/app/test_input.json
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
