apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rvc-cert
  namespace: rvc-namespace
spec:
  secretName: rvc-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.binant.io"
  dnsNames:
    - "*.binant.io"
