apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rvc-weights-pvc
  namespace: rvc-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rvc-logs-pvc
  namespace: rvc-namespace
spec:
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

